### ISSUE TITLE
Add directory for "Amazon Alexa - Delhi"

### ISSUE THREAD

**Issue by TheDreamSaver** [YashishDua/explore-communities#1]
###Community Name
Amazon Alexa - Delhi

### Event Name
Workshops and Meetups related to Amazon Alexa Development

### Link

[Slack](https://join.slack.com/t/alexadevsindia/shared_invite/enQtMzE3MDk0OTUzNjAyLWI4ODdjZGQ2NzVmMjA5ZWY2OGYxMDYzZWE0NjllZmM2NGI3NGJhNDE0MzdjYjkxNDEwMGMzYjUzODM0OWJkY2E)

[Meetup](https://www.meetup.com/Amazon-Alexa-Meetup-NCR/)

[Facebook](https://www.facebook.com/alexadelhi/)

[Twitter](https://twitter.com/alexadevs)

**Comment by YashishDua** [comment]
Added!
